[project]
name = "vb-portfolio-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "dhanabalanb", email = "dhanabalan.cloud@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.141.1",
]

[project.scripts]
vb-portfolio-ai = "vb_portfolio_ai:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
